In [1]:
import numpy as np

In [2]:
x = np.array([5, 4, -7, 11])
print(x)


[ 5  4 -7 11]


In [ ]:
y = np.array([[4, 5, 0], [3, 7, 9], [2, 1, 2]])
print(y)
# the number of squared brackets indicates the dimensions (here: two dimensions)

In [7]:
test = np.array([[1,2,3],[4,5,6]])
print(test)

[[1 2 3]
 [4 5 6]]


In [8]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [9]:
d3 = np.array([[[1,2],[3,4],[5,6]]])
print(d3)

[[[1 2]
  [3 4]
  [5 6]]]


In [11]:
d3l2 = np.array([[[1,2],[3,4],[5,6]],[[6,7],[9,10],[11,12]]])
print(d3l2)
# three dimensional layer with two layers

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 6  7]
  [ 9 10]
  [11 12]]]


In [13]:
b = np.arange(10).reshape(2, 5) 
print(b)
# another way to create an array, not with a list but with a function
# numbers from 0 to 9 with 2 rows and 5 columns

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
btest = np.arange(100).reshape(4,25)
print(btest)
# first number represents the number of layers, second and third the rows and columns
# the numbers must fit (the arange value must be the product of dim*nrow*ncol)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]


In [26]:
type(b)
# to check if it is an numpy array

numpy.ndarray

In [54]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


Exercise1:Create a 3-dimensional array using np.arange() and reshape and check for shape, size, dimension

In [38]:
btest3 = np.arange(2,38).reshape(3,2,6)
print(btest3)

[[[ 2  3  4  5  6  7]
  [ 8  9 10 11 12 13]]

 [[14 15 16 17 18 19]
  [20 21 22 23 24 25]]

 [[26 27 28 29 30 31]
  [32 33 34 35 36 37]]]


In [39]:
type(btest3)

numpy.ndarray

In [40]:
btest3.shape

(3, 2, 6)

In [41]:
btest3.shape
# to check nrow and ncol

(3, 2, 6)

In [42]:
btest3.size


36

In [44]:
btest3.ndim

3

In [36]:
btest3.ndim

3

Exercise2:Extract the value 15 from the z array above by indexing

In [ ]:
##array slice

In [48]:
btest3[1,0,1]

15

In [55]:
z[1, 2, :]

array([16, 17, 18])

In [56]:
y[:2, :]

array([[4, 5, 0],
       [3, 7, 9]])

In [57]:
y[1:, :]

array([[3, 7, 9],
       [2, 1, 2]])

Exercise3:Extract the 2nd layer, first and 2nd rows and all columns from the z array above by slice and indexing

In [53]:
z[1,:2,:]

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
##vectorizing and summarizing

In [58]:
x+2

array([ 7,  6, -5, 13])

In [64]:
btest3+1

array([[[ 3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26]],

       [[27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38]]])

In [59]:
x-1

array([ 4,  3, -8, 10])

In [60]:
x**2

array([ 25,  16,  49, 121])

In [61]:
np.abs(x)

array([ 5,  4,  7, 11])

In [67]:
np.max(x)

11

In [68]:
np.max(btest3)

37

In [69]:
np.median(btest3)

19.5

In [63]:
np.median(x)

4.5

Exercise4: Write a Python program to find the median of a given array of numbers with for and if loop

In [ ]:
xsort = np.sort(x)
mid = xsort.size/2
xsort[mid]
print(xsort)
print(mid)


In [ ]:
xsort = np.sort(x)
mid = xsort.size/2
if xsort.size%2==0: 
    median = (xsort[mid]+xsort[mid]+1)/2]
    print(median)
    else median = xsort[mid]


Exercise5: Write a Python program to find the median of a given array of numbers using vectorizing

In [ ]:
x<5 

In [ ]:
x==11

In [ ]:
~(x > 1)

In [ ]:
##masks for subsetting

In [ ]:
x[x < 5]

In [ ]:
x[x < 5]=40
x


Exercise6: Substitute the values from array x which are not greater than 20,or equal to 11 with 30 (use logical operator not and or)

In [ ]:
np.sum(x)

In [ ]:
np.sum(x<35)

In [ ]:
np.sum(y, axis=0)

In [ ]:
np.sum(y, axis=1)

In [ ]:
##row-column
np.sum(z, axis=0)

In [ ]:
##column-layer
np.sum(z, axis=1)

In [ ]:
##row-layer
np.sum(z, axis=2)

Exercise7: Calculate the mean of all column in each layer from array z.

In [ ]:
## ploting an array

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
h = y.flatten()
h

In [ ]:
plt.hist(h);

In [ ]:
plt.plot(y[1, :]);

In [ ]:
plt.plot(y[:, 1]);

In [ ]:
plt.plot(y);

In [ ]:
plt.imshow(y);

In [ ]:
##practice with plotting on different arrays

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

plt.hist(data, bins=[0,2,4,6,8,10])
plt.title('My Histogram')
plt.xlabel('Interval')
plt.ylabel('Frequency')
plt.show()


Exercise8: Given an 2D array of numbers, plot a graph that displays the sum of each element in the column.


Reference: https://docs.python.org
https://geobgu.xyz/py/numpy.html 