In [1]:
import numpy as np

In [2]:
x = np.array([5, 4, -7, 11])
print(x)


[ 5  4 -7 11]


In [3]:
y = np.array([[4, 5, 0], [3, 7, 9], [2, 1, 2]])
print(y)

[[4 5 0]
 [3 7 9]
 [2 1 2]]


In [4]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [5]:
b = np.arange(10).reshape(2, 5) 
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
type(b)

numpy.ndarray

In [7]:
b.shape

(2, 5)

In [8]:
b.size

10

In [9]:
b.ndim

2

Exercise1:Create a 3-dimensional array using np.arange() and reshape and check for shape, size, dimension

In [10]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


Exercise2:Extract the value 15 from the z array above by indexing

In [11]:
##array slice

In [12]:
z[1, 2, :]

array([16, 17, 18])

In [13]:
y[:2, :]

array([[4, 5, 0],
       [3, 7, 9]])

In [14]:
y[1:, :]

array([[3, 7, 9],
       [2, 1, 2]])

Exercise3:Extract the 2nd layer, first and 2nd rows and all columns from the z array above by slice and indexing

In [15]:
##vectorizing and summarizing

In [16]:
x+2

array([ 7,  6, -5, 13])

In [17]:
x-1

array([ 4,  3, -8, 10])

In [18]:
x**2

array([ 25,  16,  49, 121])

In [19]:
np.abs(x)

array([ 5,  4,  7, 11])

In [20]:
np.max(x)

11

In [21]:
np.median(x)

4.5

Exercise4: Write a Python program to find the median of a given array of numbers with for and if loop

In [35]:
xsort = np.sort(x)
mid = int(len(x)/2)
if xsort.size%2==0: 
    median = (xsort[mid]+xsort[mid+1])/2
else: median = xsort[mid]
print("Median: " + str(median))

Median: 8.0


Exercise5: Write a Python program to find the median of a given array of numbers using vectorizing

In [38]:
x<5 
# which elements in the array are smaller than 5

array([False,  True,  True, False])

In [39]:
x==11

array([False, False, False,  True])

In [43]:
~(x > 1)
# ~ usually means "round", but here it means "not", so it´s like an inversion

array([False, False,  True, False])

In [41]:
x>1

array([ True,  True, False,  True])

In [ ]:
##masks for subsetting

In [45]:
x[x < 5]
# return the elements for which the condition is true

array([ 4, -7])

In [46]:
x[x < 5]=40
x
# replace all values lower than 5 with 40

array([ 5, 40, 40, 11])

Exercise6: Substitute the values from array x which are not greater than 20,or equal to 11 with 30 (use logical operator not and or)

In [54]:
x[~(x>20)]

array([ 5, 11])

In [64]:
x[~(x>20)|(x==11)]=30
x

array([30, 40, 40, 30])

In [65]:
np.sum(x)

140

In [71]:
np.sum(x<35)
# if a conditional statement is used, it counts the "TRUE" values

2

In [72]:
np.sum(x[x<35])


60

In [73]:
np.sum(y%2)

5

In [70]:
y

array([[4, 5, 0],
       [3, 7, 9],
       [2, 1, 2]])

In [67]:
np.sum(y, axis=0)

array([ 9, 13, 11])

In [68]:
np.sum(y, axis=1)

array([ 9, 19,  5])

In [75]:
z

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [77]:
##row-column
# for multidmensional arrays: axis = 0 is for each row?!
np.sum(z, axis=0)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [76]:
## sum of each column
np.sum(z, axis=1)

array([[12, 15, 18],
       [39, 42, 45]])

In [ ]:
##row-layer
np.sum(z, axis=2)

Exercise7: Calculate the mean of all column in each layer from array z.

In [ ]:
## ploting an array

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
h = y.flatten()
h

In [ ]:
plt.hist(h);

In [ ]:
plt.plot(y[1, :]);

In [ ]:
plt.plot(y[:, 1]);

In [ ]:
plt.plot(y);

In [ ]:
plt.imshow(y);

In [ ]:
##practice with plotting on different arrays

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

plt.hist(data, bins=[0,2,4,6,8,10])
plt.title('My Histogram')
plt.xlabel('Interval')
plt.ylabel('Frequency')
plt.show()


Exercise8: Given an 2D array of numbers, plot a graph that displays the sum of each element in the column.


Reference: https://docs.python.org
https://geobgu.xyz/py/numpy.html 